// Generated by CoffeeScript 1.9.0
(function() {
  $(document).ready(function() {
    $('button').hide();
    $(window).scroll(function() {
      if ($(window).scrollTop() > 100) {
        return $('button').fadeIn(500);
      } else {
        return $('button').fadeOut(500);
      }
    });
    return $('button').click(function() {
      return $('html').animate({
        scrollTop: 0
      }, 1000);
    });
  });

}).call(this);
